<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<title>Merdu Music CD Shop</title>';
echo '<link rel="stylesheet" href="LabCSS\mystyle.css">';
echo '</head>';
echo '<header>';
echo '<h1><img src="https://image.flaticon.com/icons/png/512/32/32328.png" style="width: 30px; height:30px;">';
echo 'Merdu Music CD Shop';
echo '<a href="#cart" style="float: right; text-decoration: none;">Shopping Cart</a>';
echo '<img src="https://i.pinimg.com/originals/15/4f/df/154fdf2f2759676a96e9aed653082276.png" style="width: 30px; height:30px; float: right;" >';
echo '</h1>';
echo '<div class="topnav">';
echo '<a class="active" href="CDShop.html">Home</a>';
echo '<a href="CDList.html">CDs</a>';
echo '<a href="#events">Events</a>';
echo '<a href="#about">About</a>';
echo '<a href="registration.html">Register</a>';
echo '</div>';
echo '</header>';
echo '<body>';
echo '<div class="sidenav">';
echo '<b>Categories</b><br>';
echo '<a href="kpop.html">K-pop</a>';
echo '<a href="jpop.html">J-pop</a>';
echo '<a href="anime.html">Anime</a>';
echo '<a href="soundtrack.html">Soundtrack</a>';
echo '<a href="western.html">Western Music</a>';
echo '</div>';
echo '<br>';
echo '<h2 style="border-bottom: solid; ">TopSellers</h2>';
echo '<table style="width: 100%; table-layout: fixed;" >';
echo '<tr>';
echo '<td>';
echo '<br>';
echo '<img src="https://cf.shopee.com.my/file/093cb6cb3481549aa4329514c27d5bd7" style="width: 300px; height:300px;" ><br>';
echo '<a href="VBS.html">Vivid Bad Squad - Ready Steady / Forward</a>';
echo '</td>';
echo '<td>';
echo '<img src="https://upload.wikimedia.org/wikipedia/en/2/21/BTS_-_Map_of_the_Soul_7.png" style="width: 300px; height:300px;" ><br>';
echo '<a href="BTS.html">BTS - Map of the Soul: 7</a>';
echo '</td>';
echo '<td>';
echo '<img src="https://static.wikia.nocookie.net/ladygaga/images/7/75/TheFame.jpg/revision/latest/scale-to-width-down/2000?cb=20110410191050" style="width: 300px; height:300px;" ><br>';
echo '<a href="LadyGaga.html">The Fame - Lady Gaga</a>';
echo '</td>';
echo '</tr>';
echo '</table>';
echo '<br>';
echo '<h2 style="border-bottom: solid; ">New Releases</h2>';
echo '<table style="width: 100%; table-layout: fixed;">';
echo '<tr>';
echo '<td>';
echo '<img src="https://upload.wikimedia.org/wikipedia/en/9/90/Twice_-_Eyes_Wide_Open.png" style="width: 300px; height:300px;" ><br>';
echo '<a href="Twice.html">EYES WIDE OPEN - TWICE 2nd Album </a>';
echo '</td>';
echo '<td>';
echo '<br>';
echo '<img src="https://static.wikia.nocookie.net/finalfantasy/images/a/ab/Final_Fantasy_VII_Remake_Original_Soundtrack_Cover.jpg/revision/latest?cb=20200527013722" style="width: 300px; height:300px;" ><br>';
echo '<a href="FF7.html">Final Fantasy VII Remake Original Soundtrack</a>';
echo '</td>';
echo '<td>';
echo '<img src="https://m.media-amazon.com/images/I/71nRHTIxYfL._SL1044_.jpg" style="width: 300px; height:300px;" ><br>';
echo '<a href="Spyair.html">Million - Spyair</a>';
echo '</td>';
echo '</tr>';
echo '</table>';
echo '</body>';
echo '<footer>';
echo '<ul>';
echo '<li><a href="CDShop.html">Home</a></li>';
echo '<li><a href="CDList">CDs</a></li>';
echo '<li><a href="#events">Events</a></li>';
echo '<li><a href="#about">About</a></li>';
echo '<li><a href="registration.html">Register</a></li>';
echo '</ul>';
echo '</footer>';
echo '</html>';
?>